service: lambda-comments

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, env:AWS_DEFAULT_REGION, 'us-east-1'}
  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_CALLBACK_URI: ${env:TWITTER_CALLBACK_URI}

functions:
  hello:
    handler: src/handler.hello

  twitter_authenticate:
    handler: src/oauth/twitter.requestToken
    events:
      - http:
          path: twitter/authenticate
          method: get
          cors: true

  twitter_authorize:
    handler: src/oauth/twitter.authToken
    events:
      - http:
          path: twitter/authorize
          method: post
          cors: true

  twitter_user:
    handler: src/oauth/twitter.userData
    events:
      - http:
          path: twitter/user
          method: post
          cors: true
